packages/layouts/package.json
packages/layouts/src/graphviz/printToDot.ts
yarn.lock

Hi,
Firstly, I want to express my gratitude for this excellent project.
I am the author of the [ts-graphviz](https://github.com/ts-graphviz/ts-graphviz) library and while researching its usage, I came across your project. Upon inspecting it for type error workarounds, I identified an issue with the ts-graphviz library. As a result, I have released a fix for it in version [1.8.0](https://github.com/ts-graphviz/ts-graphviz/releases/tag/v1.8.0).
This pull request aims to upgrade the library and address the type issue that was affecting your project.
Thank you for considering my contribution.

Upgrade ts-graphviz and fix type problems

---

packages/cli/esbuild.mjs
packages/cli/package.json
packages/cli/src/cli.ts
packages/cli/src/cmd-export.ts
packages/cli/src/export/export-script-generator.ts
packages/cli/src/export/index.ts
packages/cli/src/export/puppeteer-page/index.tsx
packages/cli/src/export/puppeteer-page/tsconfig.json
packages/cli/tsconfig.json
packages/core/package.json
packages/diagrams/package.json
packages/diagrams/src/diagram/Diagram.tsx
yarn.lock

Adds CLI command
```
likec4 export -o folder_for_png ./likec4/sources
```

feat: export to png from CLI #71

---

examples/cloud-system/package.json
packages/layouts/src/graphviz/__snapshots__/dotLayout.spec.ts.snap
packages/layouts/src/graphviz/dotLayout.ts

fix: invalid edge rendering

---

docs/components/playground-page/playground.tsx
docs/components/playground-page/view-mmd.tsx
packages/cli/src/cmd-codegen.ts
packages/generators/src/index.ts
packages/generators/src/mmd/__snapshots__/generate-mmd.spec.ts.snap
packages/generators/src/mmd/generate-mmd.spec.ts
packages/generators/src/mmd/generate-mmd.ts
packages/generators/src/mmd/index.ts

This exports in Mermaid flowchart format, with all the same features as the D2 export, but does not attempt to export links or other enhancements available in Mermaid.

Basic export in Mermaid format

---

docs/components/playground-page/playground.tsx
docs/components/playground-page/view-mmd.tsx
packages/cli/src/cmd-codegen.ts
packages/generators/src/index.ts
packages/generators/src/mmd/__snapshots__/generate-mmd.spec.ts.snap
packages/generators/src/mmd/generate-mmd.spec.ts
packages/generators/src/mmd/generate-mmd.ts
packages/generators/src/mmd/index.ts

export mermaid

---

package.json
packages/likec4/app/likec4.css
packages/likec4/app/src/components/view-page/ShareDialog.tsx
packages/likec4/app/src/const.ts
packages/likec4/app/src/data/likec4.d.ts
packages/likec4/app/src/likec4-views.ts
packages/likec4/app/src/likec4.d.ts
packages/likec4/app/src/pages/export.page.tsx
packages/likec4/app/src/router.ts
packages/likec4/app/tsconfig.json
packages/likec4/scripts/build.ts
packages/likec4/scripts/prepack.ts
packages/likec4/src/cli/build/build.ts
packages/likec4/src/cli/build/index.ts
packages/likec4/src/cli/export/png/handler.ts
packages/likec4/src/cli/export/utils/takeScreenshot.ts
packages/likec4/src/cli/preview/index.ts
packages/likec4/src/cli/preview/preview.ts
packages/likec4/src/cli/serve/index.ts
packages/likec4/src/cli/serve/serve.ts
packages/likec4/src/vite/config.ts
packages/likec4/src/vite/plugin.ts
packages/likec4/src/vite/vite-build.ts

Allow custom base url (base path) in `likec4` CLI for static website

feat: change base url in `likec4` CLI

---

docs/pages/docs/dsl/relations.mdx
docs/pages/docs/dsl/specification.mdx

Add docs for relationships

---

packages/diagrams/src/diagram/Nodes.tsx
packages/diagrams/src/diagram/icons/ZoomIn.tsx
packages/diagrams/src/diagram/icons/index.ts
packages/diagrams/src/diagram/shapes/Compound.tsx
packages/likec4/app/src/components/view-page/DisplayModeSelector.tsx
packages/likec4/app/src/components/view-page/ViewActionsToolbar.tsx

feat(diagrams): add icon to elements to indicate they include a sub-view #361

---

packages/core/src/errors/errors.spec.ts
packages/core/src/errors/index.ts
packages/language-server/src/module.ts
packages/layouts/src/graphviz/DotLayouter.ts
packages/layouts/src/graphviz/dotLayout.ts
packages/layouts/src/index.ts
packages/vscode/package.json
packages/vscode/src/common/C4Model.ts
packages/vscode/src/common/ExtensionController.ts
packages/vscode/src/common/GraphvizLayout.ts
packages/vscode/src/logger.ts
packages/vscode/src/node/BinaryGraphvizLayout.ts
packages/vscode/src/node/extension.ts
yarn.lock

VSCode configuration to use local graphviz binary

---

docs/pages/docs/dsl/relations.mdx
packages/core/src/types/relation.ts
packages/core/src/utils/guards.ts
packages/language-server/src/__tests__/model-relation.spec.ts
packages/language-server/src/ast.ts
packages/language-server/src/like-c4.langium
packages/language-server/src/model/model-builder.spec.ts
packages/language-server/src/model/model-builder.ts
packages/language-server/src/model/model-parser.ts

feat: add links to relationships

---

packages/layouts/src/graphviz/DotLayouter.ts
packages/layouts/src/graphviz/__snapshots__/dotLayout.spec.ts.snap
packages/layouts/src/graphviz/__snapshots__/printToDot.spec.ts.snap
packages/layouts/src/graphviz/binary/BinaryGraphvizLayout.ts
packages/layouts/src/graphviz/dotLayout.ts
packages/layouts/src/graphviz/printToDot.ts
packages/layouts/src/graphviz/types.ts
packages/layouts/src/graphviz/utils.ts

- improve logging when dot-binary is used
- decrease number of nodes to group 7 -> 5 (resolves #614)
- relations with group elements (resolves #530)

feat: relations with container elements

---

packages/likec4/package.json
packages/likec4/src/cli/export/png/handler.ts
packages/likec4/src/cli/export/utils/takeScreenshot.ts
packages/likec4/src/logger.ts
yarn.lock

Multiple reports that sometimes cli export in docker timed out\
I guess that I was abusing playwright by creating a page for each diagram
Fixes #634

fix(cli): reuse playwright page for screenshots

---

packages/graph/src/compute-view/utils/applyViewRuleStyles.ts

remove rudiments

---

packages/diagram/src/LikeC4Diagram.props.ts
packages/diagram/src/LikeC4Diagram.tsx
packages/diagram/src/StaticLikeC4Diagram.tsx
packages/diagram/src/globals.css.ts
packages/diagram/src/ui/DiagramTitlePanel.css.ts
packages/diagram/src/ui/DiagramTitlePanel.tsx
packages/diagram/src/xyflow/XYFlow.tsx
packages/diagram/src/xyflow/nodes/compound/CompoundNode.css.ts
packages/language-server/src/model/model-parser.ts
packages/likec4/app/react/components/LikeC4Browser.css.ts
packages/likec4/app/react/components/LikeC4Browser.tsx
packages/likec4/app/react/components/LikeC4ViewElement.tsx
packages/likec4/app/react/components/styles.css.ts
packages/likec4/app/src/routes/export.$viewId.tsx
packages/likec4/app/webcomponent/LikeC4Browser.tsx
packages/likec4/app/webcomponent/LikeC4View.tsx

feat: diagram title panel

---

apps/docs/src/content/docs/dsl/relationships.mdx
packages/diagram/src/xyflow/edges/edges.css.ts
packages/language-server/src/__tests__/model-relation.spec.ts
packages/language-server/src/like-c4.langium
packages/language-server/src/model-graph/compute-view/compute.ts
packages/language-server/src/model/model-builder.spec.ts
packages/language-server/src/model/model-parser.ts

An implementation for https://github.com/likec4/likec4/issues/576

Added visualiztion for technology and extended syntax for definining it

---

apps/docs/src/content/docs/dsl/model.mdx
apps/docs/src/content/docs/dsl/relationships.mdx
apps/docs/src/content/docs/dsl/views.mdx
examples/cloud-system/model.c4
packages/core/src/types/element.ts
packages/core/src/types/relation.ts
packages/core/src/types/view.ts
packages/diagram/src/ui/DiagramTitlePanel.tsx
packages/diagram/src/xyflow/nodes/element/ElementLink.tsx
packages/language-server/src/__tests__/model-links.spec.ts
packages/language-server/src/ast.ts
packages/language-server/src/like-c4.langium
packages/language-server/src/model/model-builder.spec.ts
packages/language-server/src/model/model-builder.ts
packages/language-server/src/model/model-parser.ts

Implementation for https://github.com/likec4/likec4/issues/871
If provided, title is shown in UI instead of url. 
If no title provided url is shown.

Extended dsl syntax to allow titles for links

---

apps/docs/package.json
yarn.lock

Revert "fix(deps): update dependency astro to ~4.15.2"

---

packages/diagram/src/state/diagramStore.ts
packages/diagram/src/ui/top-left/TopLeftPanel.tsx
packages/diagram/src/utils/vector.ts
packages/diagram/src/xyflow/edges/RelationshipEdge.tsx

Fixed issue with control point deletion being reset on selection change
Added control point insertion on right click
Added "Reset all control points" command to simplify layout editing. **Before**:
After:

Minor improvements to edge editing

---

apps/docs/src/content/docs/tooling/model-api.mdx
packages/diagram/src/LikeC4CustomColors.tsx
packages/diagram/src/LikeC4Diagram.css.ts
packages/diagram/src/globals.css.ts
packages/diagram/src/mantine.css.ts
packages/diagram/src/theme-vars.ts
packages/diagram/src/ui/DiagramTitlePanel.css.ts
packages/diagram/src/ui/DiagramTitlePanel.tsx
packages/diagram/src/ui/DynamicViewWalkthrough.css.ts
packages/diagram/src/ui/OptionsPanel.css.ts
packages/diagram/src/ui/notation/NotationPanel.css.ts
packages/diagram/src/ui/notation/NotationPanel.tsx
packages/diagram/src/ui/top-left/ChangeAutoLayoutButton.tsx
packages/diagram/src/ui/top-left/TopLeftPanel.tsx
packages/diagram/src/ui/top-left/_shared.ts
packages/diagram/src/ui/top-left/styles.css.ts
packages/diagram/src/xyflow/XYFlowInner.tsx
packages/diagram/src/xyflow/edges/RelationshipsDropdownMenu.css.ts
packages/diagram/src/xyflow/edges/RelationshipsDropdownMenu.tsx
packages/diagram/src/xyflow/edges/edges.css.ts
packages/diagram/src/xyflow/nodes/compound/CompoundNode.css.ts
packages/diagram/src/xyflow/nodes/element/ElementLink.css.ts
packages/diagram/src/xyflow/nodes/element/element.css.ts
packages/likec4/app/src/components/sidebar/DiagramTree.css.ts
packages/likec4/app/src/components/sidebar/DiagramsTree.tsx
packages/likec4/app/src/routes/view.$viewId.editor.tsx
packages/vscode-preview/src/App.css.ts
packages/vscode/src/ExtensionController.ts

Consolidates theme imports by updating references to a unified `theme-vars` file, improving code organization and maintainability. Minor style adjustments were also made to various components for consistency.

minor visual improvements

---

packages/diagram/src/xyflow/edges/RelationshipEdge.tsx

A control point was deleted on the mouse down event. Thus, the mouse up event was routed to canvas. Canvas clears selected objects list on mouse events, which triggers edge update and reverts initial control points array.
Moved control point deletion into mouse up handler to ensure that mouse up event will be handled by control point and not by canvas.
Split onControlPointerDown into two handlers according to the pressed button.

Fix deleted control point being reverted on mouse up

---

packages/language-server/src/formatting/LikeC4Formatter.spec.ts
packages/language-server/src/formatting/LikeC4Formatter.ts

Fixed extra space in dynamic step (#1056)
Also added format rules for parallel steps

Fixed extra space in dynamic step (#1056)

---

packages/diagram/src/xyflow/useLayoutConstraints.ts

Fix: Unable to drag multiple nodes

---

packages/likec4/app/src/const.js
packages/likec4/app/src/global.d.ts
packages/likec4/app/src/routes/view.$viewId.d2.tsx

Resolves #1060
```sh
VITE_KROKI_D2_SVG_URL='https://your-kroki/' likec4 start
```

patch: add krokiD2SvgUrl configuration

---

packages/core/src/types/view-changes.ts
packages/diagram/src/ui/top-left/ChangeAutoLayoutButton.tsx
packages/diagram/src/ui/top-left/styles.css.ts
packages/language-server/src/model-change/changeViewLayout.ts
packages/language-server/src/view-utils/manual-layout.ts

feat: change layout spacings from the UI

---

apps/docs/src/content/docs/dsl/views.mdx
packages/core/src/builder/Builder.ts
packages/core/src/model/__test__/fixture.ts
packages/core/src/types/global.ts
packages/core/src/types/index.ts
packages/core/src/types/model.ts
packages/core/src/types/view.ts
packages/language-server/src/ast.ts
packages/language-server/src/like-c4.langium
packages/language-server/src/lsp/CompletionProvider.spec.ts
packages/language-server/src/model/__snapshots__/model-builder.spec.ts.snap
packages/language-server/src/model/model-builder.spec.ts
packages/language-server/src/model/model-builder.ts
packages/language-server/src/model/model-parser.ts
packages/language-server/src/references/scope-computation.ts
packages/language-server/src/validation/index.ts
packages/language-server/src/validation/specification.ts
packages/language-server/src/view-utils/index.ts
packages/language-server/src/view-utils/resolve-global-rules.spec.ts
packages/language-server/src/view-utils/resolve-global-rules.ts
packages/vscode-preview/src/state.ts

Define global styles that can be applied to any views in the document.
This is the second PR of a series aiming to replace #1058

feat: global styles

---

packages/language-server/src/model/model-parser.spec.ts
packages/language-server/src/model/model-parser.ts

Fixes where condition being ignored by if it is followed by 'with' expression.

Fix on #1144

---

packages/diagram/src/LikeC4Diagram.tsx
packages/diagram/src/state/DiagramContext.tsx
packages/diagram/src/state/diagram-to-xyflow.ts
packages/diagram/src/state/diagramStore.ts

Fixes React component filter stopped working. Version =>1.13.0
Resolves: #1145

fix(react): react component filter stopped working #1145

---

apps/docs/likec4.tmLanguage.json
apps/docs/src/content/docs/dsl/views.mdx
apps/playground/likec4.tmLanguage.json
packages/core/src/builder/Builder.ts
packages/core/src/types/global.ts
packages/core/src/types/model.ts
packages/core/src/types/view.ts
packages/language-server/src/ast.ts
packages/language-server/src/model-graph/LikeC4ModelGraph.ts
packages/language-server/src/model-graph/compute-view/__test__/fixture.ts
packages/language-server/src/model-graph/compute-view/__test__/global-style-expr.spec.ts
packages/language-server/src/model-graph/compute-view/compute.ts
packages/language-server/src/model-graph/dynamic-view/compute.ts
packages/language-server/src/model/model-builder.ts
packages/language-server/src/model/model-parser.ts
packages/language-server/src/view-utils/index.ts
packages/language-server/src/view-utils/resolve-global-rules.spec.ts
packages/language-server/src/view-utils/resolve-global-rules.ts
packages/vscode/likec4.tmLanguage.json

Global style rules and predicates are evaluated at same place as regular ones (inside view "computers").
See https://github.com/likec4/likec4/pull/1173#issuecomment-2452827294

refactor: update global rules handling

---

packages/language-server/src/model-graph/compute-view/__test__/fixture.ts
packages/language-server/src/model-graph/compute-view/compute.spec.ts
packages/language-server/src/model-graph/compute-view/compute.ts
packages/language-server/src/model-graph/utils/applyViewRuleStyles.spec.ts
packages/language-server/src/model-graph/utils/applyViewRuleStyles.ts
packages/language-server/src/model-graph/utils/elementExpressionToPredicate.spec.ts

There were several issues on predicates during the last two weeks.
It seems that there is a lack of some unit tests.

Improve test coverage

---

apps/docs/likec4.tmLanguage.json
apps/playground/likec4.tmLanguage.json
packages/core/src/model/LikeC4Model.ts
packages/core/src/types/_common.ts
packages/core/src/types/element.ts
packages/diagram/src/xyflow/nodes/compound/CompoundNode.css.ts
packages/diagram/src/xyflow/nodes/compound/CompoundNode.tsx
packages/diagram/src/xyflow/nodes/element/ElementNode.tsx
packages/diagram/src/xyflow/nodes/element/element.css.ts
packages/diagram/src/xyflow/nodes/shared/ElementIcon.tsx
packages/language-server/src/__tests__/model.spec.ts
packages/language-server/src/__tests__/specification.spec.ts
packages/language-server/src/like-c4.langium
packages/language-server/src/lsp/SemanticTokenProvider.ts
packages/language-server/src/model-graph/compute-view/__test__/__snapshots__/legacy.spec.ts.snap
packages/language-server/src/model-graph/compute-view/__test__/custom-element-expr.spec.ts
packages/language-server/src/model-graph/compute-view/__test__/fixture.ts
packages/language-server/src/model-graph/compute-view/__test__/legacy.spec.ts
packages/language-server/src/model-graph/compute-view/compute.ts
packages/language-server/src/model-graph/dynamic-view/compute.ts
packages/language-server/src/model-graph/utils/applyCustomElementProperties.ts
packages/language-server/src/model-graph/utils/applyViewRuleStyles.ts
packages/vscode-preview/vite.config.ts
packages/vscode/likec4.tmLanguage.json

feat: disable icon and icon on containers

---

packages/layouts/src/graphviz/dot-labels.ts

fix(diagram): do not render long description texts

---

apps/playground/package.json
apps/playground/src/main.tsx
packages/diagram/package.json
packages/diagram/src/LikeC4Diagram.props.ts
packages/diagram/src/LikeC4Diagram.tsx
packages/diagram/src/LikeC4Search.tsx
packages/diagram/src/StaticLikeC4Diagram.tsx
packages/diagram/src/state/diagramStore.ts
packages/generators/src/react-next/generate-react-next.ts
packages/likec4/app/react/components/LikeC4Browser.tsx
packages/likec4/app/react/components/LikeC4ViewEmbedded.tsx
packages/likec4/app/react/components/index.ts
packages/likec4/app/src/main.tsx
packages/likec4/app/src/routes/export.$viewId.tsx
packages/likec4/app/webcomponent/LikeC4Browser.tsx
packages/likec4/app/webcomponent/LikeC4View.tsx
packages/likec4/app/webcomponent/webcomponent.tsx
packages/likec4/package.json
packages/vscode-preview/package.json
packages/vscode-preview/src/App.tsx
packages/vscode-preview/src/main.tsx
yarn.lock

Implemented search for views and nodes in current view with @mantine/spotlight component.
Please, check that I've covered all export scenarios (static site, webcomponent etc.). I suspect that I could miss something.

Diargram search (#1235)

---

packages/diagram/src/LikeC4Diagram.tsx
packages/diagram/src/LikeC4Search.tsx
packages/diagram/src/state/diagramStore.ts
packages/diagram/src/ui/top-left/TopLeftPanel.tsx

Follow up to #1244.
1. Add search button to the TopLeftPanel.
2. Add highlighting of matched keywords to diagram search.

Highlight in Diagram Search

---

packages/diagram/src/xyflow/nodes/element/ElementNode.tsx
packages/diagram/src/xyflow/nodes/element/element.css.ts

Hi, @davydkov !
In response to #1242 I added button back. Fill free to reject this commit if this does not match with your vision of the tool UX.

#1242 Added button to open relationships overlay

---

packages/likec4/app/webcomponent/shadow.css

This should fix the main problem in #1241

Fixed styles for webcomponent

---

apps/docs/src/content/docs/dsl/views.mdx
packages/core/src/builder/Builder.view.ts
packages/core/src/types/expression.ts
packages/language-server/src/model-graph/compute-view/predicates.ts

Update documentation for suffix predicates

---

packages/diagram/src/ui/DiagramTitlePanel.tsx
packages/diagram/src/ui/Link.tsx
packages/diagram/src/xyflow/edges/RelationshipsDropdownMenu.tsx

Description and links are added to the context menu of a relationship

---

packages/language-server/src/model/model-parser.ts
packages/layouts/src/graphviz/dot-labels.ts

fix: allow carriage return in title and description

---

packages/vscode/src/LikeC4Model.ts
packages/vscode/src/const.ts

fix(vscode): invalid usage of performance marks #1350

---

packages/core/src/model/view/EdgeModel.ts

Fixed relation being yielded twice (#1364)

---

packages/diagram/src/state/diagramStore.ts

Closes #1323
Thanks to @arthurbellis for the hint.

Fix 'reset connection points' on self-referencing relations

---

apps/docs/src/content/docs/dsl/Deployment/views.mdx

Updated docs after #1379

---

packages/core/src/compute-view/element-view/utils.spec.ts
packages/core/src/compute-view/element-view/utils.ts

fix: incorrect merge of relation labels

---

apps/docs/likec4.tmLanguage.json
apps/docs/src/content/docs/dsl/views.mdx
apps/playground/likec4.tmLanguage.json
packages/core/src/compute-view/element-view/__test__/fixture.ts
packages/core/src/compute-view/element-view/__test__/relation-expr.spec.ts
packages/core/src/compute-view/element-view/predicates.ts
packages/core/src/compute-view/utils/relationExpressionToPredicates.spec.ts
packages/core/src/compute-view/utils/relationExpressionToPredicates.ts
packages/core/src/types/operators.spec.ts
packages/core/src/types/operators.ts
packages/diagram/src/state/diagram-to-xyflow.ts
packages/language-server/src/__tests__/model-relation.spec.ts
packages/language-server/src/like-c4.langium
packages/language-server/src/lsp/SemanticTokenProvider.ts
packages/language-server/src/model/model-parser-where.ts
packages/language-server/src/model/model-parser.spec.ts
packages/vscode/likec4.tmLanguage.json

Implemented predicates on participants of the relation for element views

---

packages/diagram/src/controls/action-button-bar/ActionButtonBar.tsx

Added key prop for action bar content

---

packages/diagram/src/state/diagramStore.ts
packages/diagram/src/xyflow/nodes/compound/CompoundNode.tsx
packages/diagram/src/xyflow/nodes/element/ElementNode.tsx

Hide element toolbar when more then one element selected

---

packages/diagram/src/overlays/edge-details/use-layouted-edge-details.ts
packages/diagram/src/overlays/element-details/TabPanelRelationships.tsx
packages/diagram/src/overlays/element-details/TabPanelStructure.tsx
packages/diagram/src/overlays/relationships-of/use-layouted-relationships.ts

I'm not sure, that covered all the places and I don't have safari browser for test. But at least this should fix the problem in the original issue and hopefully most of the similar problems which have not been reported yet.
Closes #1425

Fix for '<iterator object>.<array function> is not a function'

---

packages/likec4/app/react/components/LikeC4Browser.tsx

Fix overlay transparency in FF

---

packages/diagram/src/overlays/relationships-of/xyflow/RelationshipEdge.tsx
packages/diagram/src/xyflow/edges/RelationshipEdge.tsx
packages/diagram/src/xyflow/edges/utils.ts

Adjusted label and endpoint position of relationships on manual layout

---

packages/diagram/src/likec4diagram/custom/edges/utils.ts
packages/diagram/src/overlays/relationships-browser/SelectElement.tsx
packages/vscode-preview/vite.config.ts

Hi, @davydkov 
Tracked problem to these commented aliases. Works at least as a quick fix.
Closes #1471

Fixed broken layout in vscode previes

---

packages/language-server/bin/likec4-language-server.mjs
packages/language-server/package.json
packages/language-server/src/LikeC4FileSystem.ts
packages/language-server/src/Rpc.ts
packages/language-server/src/model/deployments-index.ts
packages/language-server/src/model/fqn-index.ts
packages/language-server/src/model/model-builder.ts
packages/language-server/src/model/model-parser.ts
packages/language-server/src/utils/disposable.ts
packages/language-server/src/utils/index.ts
packages/language-server/src/validation/_shared.ts
packages/language-server/src/validation/index.ts
yarn.lock

Allowing to start likec4 language server as command line utility

feat(lsp): `likec4-language-server` bin entry point

---

packages/language-server/build.config.ts

Fix build of language-server in dev environment

---

packages/diagram/src/base/example/_types.ts
packages/diagram/src/base/example/useViewToNodesEdges.ts
packages/diagram/src/base/primitives/compound/CompoundTitle.css.ts
packages/diagram/src/base/primitives/compound/CompoundTitle.tsx
packages/diagram/src/likec4diagram/types.ts
packages/diagram/src/likec4diagram/useViewToNodesEdges.ts
packages/diagram/src/overlays/relationship-details/_types.ts
packages/diagram/src/overlays/relationship-details/useLayoutedDetails.ts
packages/diagram/src/overlays/relationships-browser/_types.ts
packages/diagram/src/overlays/relationships-browser/useViewToNodesEdges.ts

Added icons to the compound title

---

packages/language-server/src/lsp/SemanticTokenProvider.ts

Added semantic tokens for global styles, predicates and groups

---

apps/docs/src/content/docs/dsl/workspace.mdx
packages/language-server/src/__tests__/extendsElement.spec.ts
packages/language-server/src/ast.ts
packages/language-server/src/like-c4.langium
packages/language-server/src/lsp/SemanticTokenProvider.ts
packages/language-server/src/model/__tests__/model-builder-extendElement.spec.ts
packages/language-server/src/model/model-builder.ts
packages/language-server/src/model/model-parser.ts
packages/language-server/src/model/parser/Base.ts
packages/language-server/src/model/parser/ModelParser.ts
packages/language-server/src/references/scope-provider.ts
packages/language-server/src/test/testServices.ts
packages/language-server/src/utils/elementRef.ts

feat: allow extending tags on elements 

---

apps/docs/src/content/docs/tooling/cli.mdx
packages/likec4/src/cli/options.ts
packages/likec4/src/cli/preview/index.ts
packages/likec4/src/cli/preview/preview.ts
packages/likec4/src/cli/serve/index.ts
packages/likec4/src/cli/serve/serve.ts
packages/likec4/src/vite/vite-dev.ts
packages/likec4/src/vite/vite-preview.ts

Default listen address is set to localhost
Closes #1526

Added an option to set the listen address of serve and preview commands

---

packages/diagram/src/overlays/Overlays.tsx
packages/diagram/src/overlays/relationship-details/custom/nodeTypes.tsx
packages/diagram/src/overlays/relationships-browser/custom/nodeTypes.tsx

Added 'details' button to the 'relationship browser' and 'relationship details' overlays

---

CONTRIBUTING.md

Include some more information to help prospective
contributors orient themselves with the codebase.
Based on the comment at:
https://github.com/likec4/likec4/discussions/1720#discussioncomment-12487883

docs: extend package definitions

---

packages/diagram/src/components/Link.tsx
packages/diagram/src/overlays/relationship-details/useLayoutedDetails.ts

fix: react component links error

---

packages/likec4/app/src/components/view-page/share-modal/EmbedPanel.tsx

Build embed url with respect to the current history mode

---

.github/pull_request_template.md
apps/docs/src/content/docs/tooling/Code generation/model.mdx
apps/docs/src/content/docs/tooling/Code generation/react.mdx
apps/docs/src/content/docs/tooling/Code generation/webcomponent.mdx
apps/docs/src/content/docs/tooling/cli.mdx
apps/docs/src/content/docs/tooling/vite-plugin.mdx

Closes #1920
---
- Added a [PR Template](https://github.com/MFarabi619/likec4/blob/mfarabi/docs/1920-align-shields-badges-horizontally-spaced-instead-of-vertically/.github/pull_request_template.md)
- Just a proposal, open to feedback
- Improves the external contributor experience
- Reduces review fatigue for maintainers

docs(tooling): align shields badges horizontally spaced instead of vertically

---

apps/docs/src/content/docs/dsl/specification.mdx

See https://github.com/likec4/likec4/issues/1212 and https://github.com/likec4/likec4/issues/1276
---

Docs: describe color limitations

---

packages/language-server/src/formatting/LikeC4Formatter.spec.ts
packages/language-server/src/formatting/LikeC4Formatter.ts
packages/language-server/src/test/testServices.ts
packages/vscode/package.json

Quotes normalization

---

apps/docs/src/content/docs/tooling/cli.mdx
packages/generators/src/index.ts
packages/generators/src/puml/__snapshots__/generate-puml.spec.ts.snap
packages/generators/src/puml/generate-puml.spec.ts
packages/generators/src/puml/generate-puml.ts
packages/generators/src/puml/index.ts
packages/likec4/README.md
packages/likec4/app/src/components/view-page/Header.tsx
packages/likec4/app/src/const.js
packages/likec4/app/src/routes/_single/view.$viewId.puml.tsx
packages/likec4/src/cli/codegen/handler.ts
packages/likec4/src/cli/codegen/index.ts
packages/likec4/src/vite-plugin/modules.d.ts
packages/likec4/src/vite-plugin/plugin.ts
packages/likec4/src/vite-plugin/virtuals/puml.ts

feat(codegen): Implemented export to PlantUml #1953

---

packages/likec4/app/src/components/sidebar/DiagramsTree.tsx

fix: impossible to open elements in navigation menu since 1.32.0

---

packages/language-server/src/formatting/LikeC4Formatter.ts
packages/language-server/src/like-c4.langium
packages/language-server/src/model/model-builder.spec.ts
packages/language-server/src/model/parser/DeploymentModelParser.ts
packages/language-server/src/model/parser/ModelParser.ts

fix: relationship descriptions not displayed in tooltip

---

packages/language-server/src/__tests__/model.spec.ts
packages/language-server/src/__tests__/specification.spec.ts
packages/language-server/src/like-c4.langium
packages/language-server/src/validation/property-checks.ts

fix(dsl): element identifier conflict with HEX

---

packages/likec4/src/cli/serve/index.ts
packages/likec4/src/cli/serve/serve.ts

Added 'title' option to 'serve' command

---

packages/core/src/compute-view/element-view/__test__/relation-expr.spec.ts
packages/core/src/compute-view/element-view/predicates/relation-direct.ts

fix(core): do not create loop connections from descendant selectors

---

packages/language-server/src/workspace/ProjectsManager.spec.ts
packages/language-server/src/workspace/ProjectsManager.ts

fix: name conflict in multiple projects

---

packages/language-server/src/formatting/LikeC4Formatter.spec.ts
packages/language-server/src/formatting/LikeC4Formatter.ts

fix(formatter): fixed formatting of quotes in markdown fields #2147
