packages/icons/scripts/generate.mjs
Fixes build error "../icons/all.js (3:15): Expected unicode escape" when building from git bash
=> Replaced unix path separator with path.sep to enable build on windows

packages/core/src/types/_common.ts, packages/language-server/src/model-graph/compute-view/__test__/__snapshots__/legacy.spec.ts.snap, packages/language-server/src/model-graph/compute-view/__test__/custom-relation-expr.spec.ts, packages/language-server/src/model-graph/compute-view/compute.ts, packages/language-server/src/model-graph/utils/uniqueTags.test.ts, packages/language-server/src/model-graph/utils/uniqueTags.ts
=> fix: derived connection from multiple relationships with same endpoints always picks the last relationship

packages/language-server/src/formatting/LikeC4Formatter.spec.ts, packages/language-server/src/formatting/LikeC4Formatter.ts
The second part of a composite identifier was interpreted as a kind of relation. This turned
``` 
sys1.comp1 -> sys2
```
into
```
sys1 .comp1 -> sys2
```
=> Fixed space being inserted into relation's source

packages/diagram/src/ui/options/NodeOptions.tsx
=> Fix long node names overflow in the node options panel

packages/diagram/package.json, packages/diagram/src/state/diagram-to-xyflow.ts, packages/diagram/src/state/diagramStore.ts, packages/diagram/src/ui/top-left/ManualLayoutToolsButton.tsx, packages/diagram/src/ui/top-left/TopLeftPanel.tsx, packages/diagram/src/xyflow/useLayoutConstraints.ts, yarn.lock
Implemented alignment tools for manual layouting. Alignment applied to leaf nodes only.
Also replaced @lume/kiwi solver with simple implementation. kiwi solver does not work properly for compound nodes on 2+ level with a single child. I guess that was the reason why dragging was disabled for nodes which are the only child. This workaround is acceptable for drag scenario but does not fit to align scenario: it is still required to align a node with others, even it is the only child.
Although implementation with solver is more flexible than bounding box implementation, this flexibility is not used.
=> Implemented alignment tools

apps/docs/src/content/docs/dsl/views.mdx, packages/language-server/src/like-c4.langium, packages/language-server/src/model/model-builder.spec.ts, packages/language-server/src/model/model-parser.ts
Allow defining styles local to the `views {}` blocks applicable to all views in a block.
This is the first PR of a series aiming to replace #1058
=> feat: local styles

packages/diagram/src/xyflow/edges/RelationshipEdge.tsx
Reordered layers in editing mode to allow dragging edge control points without selecting the edge. Tried to keep hover behavior as close as possible to the current implementation.
Before:
After:
=> Fix 'control points are not draggable under the edge label' (#1104)

apps/docs/src/content/docs/dsl/views.mdx, packages/language-server/src/ast.ts, packages/language-server/src/like-c4.langium, packages/language-server/src/model/model-builder.spec.ts, packages/language-server/src/model/model-parser.ts, packages/language-server/src/references/scope-computation.ts, packages/language-server/src/validation/index.ts, packages/language-server/src/validation/specification.ts
Allow defining style groups with a set of style rules that can be applied to multiple views.
This is the 3rd PR of a series aiming to replace #1058
=> feat: global style groups

apps/docs/src/content/docs/dsl/views.mdx, packages/core/src/types/view.ts, packages/language-server/src/like-c4.langium, packages/language-server/src/model/model-builder.spec.ts, packages/language-server/src/model/model-parser.ts
Allow referencing global styles and groups as the local styles in the views {} blocks applicable to all views in a block.
This is the 4th PR of a series aiming to replace #1058
=> feat: accept global styles as local styles

packages/language-server/src/model/model-builder.spec.ts, packages/language-server/src/model/model-builder.ts
Fixes #1180
Global styles were applied only when computing views. Now they are applied both during computing views and building computed models. It should cover all view computing paths.
=> fix: apply global styles in all building scenarios

apps/docs/src/content/docs/dsl/views.mdx, packages/core/src/builder/Builder.ts, packages/core/src/model/__test__/fixture.ts, packages/core/src/types/global.ts, packages/core/src/types/model.ts, packages/core/src/types/view.ts, packages/language-server/src/ast.ts, packages/language-server/src/like-c4.langium, packages/language-server/src/lsp/CompletionProvider.spec.ts, packages/language-server/src/model/__snapshots__/model-builder.spec.ts.snap, packages/language-server/src/model/model-builder.spec.ts, packages/language-server/src/model/model-builder.ts, packages/language-server/src/model/model-parser.ts, packages/language-server/src/references/scope-computation.ts, packages/language-server/src/validation/index.ts, packages/language-server/src/validation/specification.ts, packages/language-server/src/view-utils/resolve-global-rules.spec.ts, packages/language-server/src/view-utils/resolve-global-rules.ts, packages/vscode-preview/src/state.ts
This feature is intended for reusable include / exclude sequences
Architecture documentation can contain multiple views sharing the same set of repeated include and exclude sequences. Instead of repeating this set, the maintenance gets easier when the set is defined once and applied to all relevant views.
This feature allows for defining "global predicate groups" that can contain a list of include and exclude predicates. Each group can be explicitly applied to any view.
This is the 5th and final PR in the series replacing #1058
=> feat: global element and relation predicates

packages/language-server/src/index.ts, packages/likec4/src/language/module.ts
A likeC4 workspace can contain symbolic links to documents shared between multiple workspaces. The WorspaceManager is enhanced to traverse through symbolic links to correctly include documents linked by symbolic links.
=> feat: traverse symlinks in the workspace

packages/language-server/src/formatting/LikeC4Formatter.ts
It seems that langium team changed parser logic, which in turn changed the behavior of grammar utils used in formatter. Rewrote formatter to use a bit different API.
From functional point of view, nothing changed in langium API. It still does not provide a way to specify a rule as '<space> | <new line>' which is required to preserve original line breaks.
=> Fixed handler for relations after update of the langium library

packages/core/src/builder/Builder.spec.ts, packages/core/src/builder/Builder.view.ts, packages/core/src/types/expression.ts, packages/generators/src/__mocks__/data.ts, packages/language-server/src/like-c4.langium, packages/language-server/src/model-graph/LikeC4ModelGraph.ts, packages/language-server/src/model-graph/compute-view/__test__/fixture.ts, packages/language-server/src/model-graph/compute-view/__test__/legacy.spec.ts, packages/language-server/src/model-graph/compute-view/predicates.ts, packages/language-server/src/model-graph/utils/elementExpressionToPredicate.ts, packages/language-server/src/model/model-parser.ts, packages/language-server/src/view-utils/resolve-extended-views.spec.ts, packages/layouts/src/graphviz/__fixtures__/model.ts
Add a new predicate `.**` to include all of an element's descendants into a view. 
Example:
```
views {
view index {
include.saas.**
}
}
```
@davydkov, where do you want me to update the documentation? After the current documentation for `.*` might be a good place.
=> #1259 Predicate to include all descendants `.**`

apps/docs/src/content/docs/tooling/cli.mdx, packages/likec4/package.json, packages/likec4/src/cli/build/build.ts, packages/likec4/src/cli/build/index.ts, packages/likec4/src/cli/options.ts, packages/likec4/src/vite/config-app.prod.ts, packages/likec4/src/vite/config-app.ts, packages/likec4/src/vite/vite-build.ts, yarn.lock
This feature allows output to be bundled into a single static HTML file which does not require a web server (or relative files to load from a web server). So this is useful for anywhere you can attach/send just a single HTML file - like email, wikis and bug tracking systems.
=> Feat(cli): Add --output-single-file flag to build give self-contained HTML file

packages/diagram/src/overlays/relationships-browser/custom/ElementActions.tsx
Relationship browser is an awesome tool to navigate the model! It is especially useful when altering relationships between elements. But this use case does not work without the ability to navigate to these relations or elements which are endpoints of these relationships.
=> Added go-to-source button into nodes of the  relationship browser

packages/core/src/compute-view/element-view/__test__/groups.spec.ts, packages/core/src/compute-view/element-view/memory/memory.ts
Interestingly enough, Stack.from(stack) produces the reversed stack rather than copy of the original collection.
I suppose, it is because the original stack is being iterated from the topmost (newest) element to the oldest and new stack is filled by pushing items into it. Thus, the newest item in the original stack becomes the oldest in the new one.
Closes #1519
=> Fixed nesting of the groups on 3+ level

packages/diagram/src/likec4diagram/useLayoutConstraints.ts
The issue appeared after update xyflow/react. Works fine up to (including) the version 12.4.1.
In the version 12.4.2 the update mechanism for InternalNodes was refactored in order to make InternalNode immutable (https://github.com/xyflow/xyflow/commit/7cb9a8686ddf932c7fdbc36e919a78e25dee649b).
Workaround is based on assumption that value of node.internals.positionAbsolute the field is incorrect while node.position is correct. Therefore, absolute position of the node's rectangle is calculated from the position of its parent and node's relative coords.
Closes #1516
=> Workaround for incorrect value of node.internals.positionAbsolute in xyflow/react@12.4.2

packages/diagram/src/base/primitives/compound/CompoundTitle.css.ts
With value 'darken' text gets the same color as the background when node has opacity 100%.
Value screen works well with opacity values 0%-60% and 100%. At 80%-90% text is barely readable. Checked other values (lighten, plus-lighter) result mostly the same but barely readable range shifts to the 70%-80%.
Closes #1590
=> Fix styles of compound node header in light theme

packages/language-server/src/LikeC4FileSystem.ts
Fixes #1620
Update `SymLinkTraversingFileSystemProvider` to handle symbolic links without resolving paths.
* Modify `readDirectory` method to use `withSymlinks({resolvePaths: false})` option in `fdir` to prevent duplicate element names when reading files under symbolic links.
=> fix(lsp): do not resolve real filenames for symbolic links

packages/likec4/src/cli/validate/index.ts
The problem described in #1638 was related to layout computation on workspace initialization. This was solved with https://github.com/likec4/likec4/commit/7b5c98511f1ff869362422192e33aed709bbe77d#diff-e6b879e84bd696db8051d5c7aa46c0b994961913fe99fab9506f783b20570453L60-L66
--ignore-layout option seems to work as expected, thus just an alias was added.
Closes #1641
=> Added an alias for ignore-layout option

apps/docs/src/content/docs/dsl/Deployment/model.mdx, apps/docs/src/content/docs/dsl/dynamic-views.mdx, apps/docs/src/content/docs/dsl/intro.mdx, apps/docs/src/content/docs/guides/deploy-github-pages.mdx, apps/docs/src/content/docs/tooling/Code generation/react.mdx, apps/docs/src/content/docs/tooling/Code generation/webcomponent.mdx, apps/docs/src/content/docs/tooling/cli.mdx, apps/docs/src/content/docs/tooling/vite-plugin.mdx
* Switch to "web components" consistently when used in prose. Aims to align with https://github.com/WICG/webcomponents
* Fixes a few small typos
Note: I used [cspell](https://cspell.org/) to surface these issues and then worked through the results.
=> docs: update spelling

packages/language-server/src/ast.ts, packages/language-server/src/lsp/DocumentLinkProvider.ts, packages/language-server/src/model/model-parser.spec.ts, packages/language-server/src/model/parser/Base.ts, packages/language-server/src/model/parser/DeploymentModelParser.ts, packages/language-server/src/model/parser/DeploymentViewParser.ts, packages/language-server/src/model/parser/ModelParser.ts, packages/language-server/src/model/parser/SpecificationParser.ts, packages/language-server/src/model/parser/ViewsParser.ts, packages/language-server/src/workspace/ProjectsManager.ts
- Exported `ParsedElementStyle` type for better accessibility.
- Replaced the `toElementStyle` function with a more integrated approach in various parsers to enhance style property handling.
- Added new methods for parsing icon properties and element styles directly within the `BaseParser` class.
- Updated multiple parser files to utilize the new style parsing methods, ensuring consistent handling of element styles across the codebase.
=> refactor: move element style parsing and improve icon handling

packages/language-server/src/lsp/HoverProvider.ts
=> fix(vscode): VS Code plugin shows `[object Object]` for instanceOf target in hover tooltip

apps/docs/likec4.tmLanguage.json, apps/playground/likec4.tmLanguage.json, packages/language-server/src/formatting/LikeC4Formatter.ts, packages/language-server/src/like-c4.langium, packages/language-server/src/lsp/CompletionProvider.spec.ts, packages/language-server/src/lsp/CompletionProvider.ts, packages/language-server/src/model/model-parser-where.ts, packages/language-server/src/model/parser/Base.ts, packages/language-server/src/model/parser/DeploymentModelParser.ts, packages/language-server/src/model/parser/FqnRefParser.ts, packages/language-server/src/model/parser/ModelParser.ts, packages/language-server/src/references/scope-computation.ts, packages/language-server/src/validation/specification.ts, packages/vscode/likec4.tmLanguage.json
Reference to tag was defined as Hash + Id. Thus, LSP replaces the whole reference with the new value.
Splitting TagId into two terminals solves the problem at a cost of more verbose grammar.
Side effect for user - suggestions on tags are shown only after the Hash is written, on the other hand it allows us to use hash as a trigger for autocompletion.
Also, I noticed that in WhereExpressions tag value was marked as 'optional' thus the following expressions were correct:
```
include * where tag is or kind is something
```
I was not able to find any reasons for 'optional tag value' and according to unit tests it is not necessary. I removed it. Probably, that was a workaround for some problem?
---
Closes #1819
=> fix(lsp): Fixed lsp renaming for tags and relation kinds #1819

.github/renovate.json5, packages/likec4/package.json, pnpm-lock.yaml
Caused by https://github.com/bubkoo/html-to-image/issues/506
Downgrade `html-to-image` to `1.11.11`
Fixes #1211
=> fix: problems when exporting to PNG
